spring:
  datasource:
#    database-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/perfectmeal
#    username: sa
#    password: 1111
    database-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/perfectmeal
    username: root
    password: bell1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create


jwt:
  secret: bXktcHJvamVjdC1uYW1lLXBlcmZlY21lYWwtYW5kLXRoaXMtaXMtand0LWF1dGhlbnRpY2F0aW9uLXNlY3JldC1rZXktZm9yLUhTNTEyLXNpZ25XaXRo
#  access-token-expire-time: 1800000
  access-token-expire-time: 5000
  refresh-token-expire-time: 604800000
