spring:
  datasource:
    database-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/perfectmeal
    username: sa
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create


jwt:
  secret: bXktcHJvamVjdC1uYW1lLXBlcmZlY21lYWwtYW5kLXRoaXMtaXMtand0LWF1dGhlbnRpY2F0aW9uLXNlY3JldC1rZXktZm9yLUhTNTEyLXNpZ25XaXRo
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000